// Dummy data
import Location from "./models/location.js";
import mongoose from "mongoose";
const locations = [
  {
    name: "Pillai HOCL Educational Campus",
    address:
      "HOC Colony HOC School Complex Taluka Khalapur, V5VG+GQ8, Dist, HOC Colony, Panvel, Rasayani, Chambharli, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 65,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 60,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 90,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 88,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 78,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "MIDC Hill,Ambivali Tarfe Tungaratan",
    address:
      "W53F+G5R, MIDC Hill Rd, Rasayani, Parade, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.756262,
      longitude: 73.214367,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 55,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 50,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 65,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "9-12_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 70,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "6-9_pm": {
        safety_score: 68,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 65,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "The Pavilion Restrocafe",
    address:
      "The Pavilion Restrocafe, At Post Mohopada Tal Khalapur, Dist, Rasayani, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 95,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 92,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 88,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Shri Sai aishwarya hotel",
    address: "Mohopada, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 68,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 65,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 77,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "sai snacks restaurant",
    address:
      "Door No.148 First Floor, Nr. MSEB Office, Mohopada, Tal: Khalapur, Rasayani, Mohopada, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 60,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 58,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 68,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 75,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 70,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Apoorva Family Restaurant",
    address:
      "6, Dand Apta Road, Ganeshnagar, Chambharli, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 68,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 92,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 90,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 87,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 84,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Ruchi's kitchen",
    address:
      "Raut building, near RDCC Bank, Panvel, Mohopada Alias Wasambe, Rasayani, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 66,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 64,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 74,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 77,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Townhouse 82843 Hotel Somani",
    address: "Panvel, Raigad, Mumbai, Karade Kh., Maharashtra 410206, India",
    coordinates: {
      latitude: 18.976975,
      longitude: 73.123467,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 62,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 60,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 76,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 72,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Radhai Goodluck Lodge",
    address: "V5WM+PG3, Mohopada, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 55,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 53,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 65,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 68,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 72,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 68,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "SPOT ON 42765 Om Sai Prasad Resto & Bar",
    address:
      "1, Savroli - Kharpada Rd, Rasayani, Ambivali Tarf Wankhal, Maharashtra 410220, India",
    coordinates: {
      latitude: 18.777776,
      longitude: 73.202381,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 50,
        factors: {
          crime_rate: "high",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "several",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 48,
        factors: {
          crime_rate: "high",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "several",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 58,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "9-12_am": {
        safety_score: 60,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "12-3_pm": {
        safety_score: 68,
        factors: {
          crime_rate: "medium",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "few",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 65,
        factors: {
          crime_rate: "high",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
      "6-9_pm": {
        safety_score: 62,
        factors: {
          crime_rate: "high",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "several",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 60,
        factors: {
          crime_rate: "high",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "several",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Elysium Estates (Near Panvel)",
    address: "Panvel, Navi Mumbai, Maharashtra 410207, India",
    coordinates: {
      latitude: 18.976975,
      longitude: 73.123467,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 66,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 64,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 74,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 77,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "SPOT ON Om Sai Prasad Lodging",
    address:
      "1, Savroli - Kharpada Rd, Rasayani, Ambivali Tarf Wankhal, Maharashtra 410220, India",
    coordinates: {
      latitude: 18.777776,
      longitude: 73.202381,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 55,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "one",
          disturbances: "minor",
        },
      },
      "3-6_am": {
        safety_score: 53,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "one",
          disturbances: "minor",
        },
      },
      "6-9_am": {
        safety_score: 63,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_am": {
        safety_score: 65,
        factors: {
          crime_rate: "medium",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "12-3_pm": {
        safety_score: 70,
        factors: {
          crime_rate: "medium",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "3-6_pm": {
        safety_score: 68,
        factors: {
          crime_rate: "medium",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "one",
        },
      },
      "6-9_pm": {
        safety_score: 66,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "none",
          disturbances: "one",
        },
      },
      "9-12_pm": {
        safety_score: 64,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "none",
          disturbances: "one",
        },
      },
    },
  },
  {
    name: "Usarai Rainy season waterfall",
    address: "W44W+FWW, Devloli, Maharashtra 410207, India",
    coordinates: {
      latitude: 18.785426,
      longitude: 73.240641,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 60,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 58,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 68,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 72,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 73,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_pm": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
    },
  },
  {
    name: "Dimple Gardens",
    address: "V5M3+QR5, Rasayani, Maharashtra 410207, India",
    coordinates: {
      latitude: 18.781673,
      longitude: 73.223815,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 68,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 82,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 88,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Thiyya Andolan Pillai School",
    address:
      "V5VG+MH2, HOC Colony, Rasayani, Chambharli, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 73,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 87,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 92,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 90,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 88,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Parivar mart",
    address: "Parade, Maharashtra 410207, India",
    coordinates: {
      latitude: 18.766876,
      longitude: 73.217792,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 65,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 63,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 73,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 77,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 75,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Mahalaxmi Novelty (shop)",
    address:
      "Shivaji Chock, Main Market, Mohopada Alias Wasambe, Rasayani, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 67,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 65,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 77,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Lucky General Stores",
    address: "Raigad, Shop No 1, Mohopada, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 68,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 82,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 88,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Shopping Centre",
    address: "V6W8+XJ8, Lodhivali, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.772219,
      longitude: 73.227017,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 72,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 70,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 84,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 90,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 88,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 85,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "minor",
        },
      },
      "9-12_pm": {
        safety_score: 82,
        factors: {
          crime_rate: "medium",
          visibility: "low",
          road_busyness: "low",
          police_presence: "low",
          lighting: "poor",
          recent_crimes: "few",
          disturbances: "minor",
        },
      },
    },
  },
  {
    name: "Rasayani, Mohopada Mutton & Chicken Market",
    address:
      "V5WJ+R76, Dand Apta Road, Mohopada Alias Wasambe, Rasayani, Maharashtra 410222, India",
    coordinates: {
      latitude: 18.767655,
      longitude: 73.222308,
    },
    time_slot_data: {
      "12-3_am": {
        safety_score: 65,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_am": {
        safety_score: 63,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_am": {
        safety_score: 73,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_am": {
        safety_score: 77,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "12-3_pm": {
        safety_score: 83,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "high",
          police_presence: "high",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "3-6_pm": {
        safety_score: 80,
        factors: {
          crime_rate: "low",
          visibility: "high",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "good",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "6-9_pm": {
        safety_score: 78,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "medium",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
      "9-12_pm": {
        safety_score: 75,
        factors: {
          crime_rate: "low",
          visibility: "medium",
          road_busyness: "low",
          police_presence: "medium",
          lighting: "average",
          recent_crimes: "none",
          disturbances: "none",
        },
      },
    },
  },
];

const connectDB = async () => {
  try {
    await mongoose.connect(
      "mongodb+srv://onlyaddy68:5mPZQwXW2cYyzw2q@vcet.c0gng.mongodb.net/women?retryWrites=true&w=majority&appName=womenSafety",
      {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      }
    );
    console.log("MongoDB connected");
  } catch (error) {
    console.error("MongoDB connection error:", error.message);
    process.exit(1); // Exit if connection fails
  }
};

const addDummyLocations = async () => {
  try {
    await connectDB(); // Ensure DB is connected before inserting
    const result = await Location.insertMany(locations);
    console.log("Dummy locations added:", result);
    mongoose.disconnect(); // Close the connection after insertion
  } catch (error) {
    console.error("Error adding dummy locations:", error.message);
  }
};

addDummyLocations();
